### ISSUE TITLE
Manage docker hub common tags

### ISSUE THREAD

**Issue by lospejos** [orangesys/alpine-grafana#1]
Hi!
Consider managing docker hub common/default tags (such as a LATEST) for "orangesys/alpine-grafana".
Otherwise you should know exact versions of alpine-grafana to pull image successfully.
If you try to do:

`docker pull orangesys/alpine-grafana`

It will give you an error:
`manifest for orangesys/alpine-grafana:latest` not found

**Comment by gavinzhou** [comment]
@lospejos 
hi , thank you for used my docker images.
I create latest with v4.6.3.
you can get docker image with latest tag
`docker pull orangesys/alpine-grafana`
