### ISSUE TITLE
Creating directories problem

### ISSUE THREAD

**Issue by mis4s** [orangesys/alpine-grafana#2]
Hi,

There is problem on this line: https://github.com/orangesys/alpine-grafana/blob/a48369b7612d9a5c94baed0a66e659a13ae8b3e1/Dockerfile#L22

This do not create directories, like `/grafana/dashboards`, `/grafana/data` only one with name `{dashboards,data,logs,plugins}`.

```
/grafana # ls
LICENSE.md                      README.md                       bin                             data                            logs                            public                          tools
NOTICE.md                       VERSION                         conf                            grafana.db                      plugins                         scripts                         {dashboards,data,logs,plugins}
```

Steps to reproduce:

1. Start container
2. Access container like `docker exec -ti grafana_server_1 sh`
3. `ls -al /grafana`

**Comment by gavinzhou** [comment]
hi, @Viperoo
thank your issue. I fixed it .
Could you try again. Let me know if anything problem.

```
docker run -it -d --rm --entrypoint ash orangesys/alpine-grafana

docker run -it --rm --entrypoint ash orangesys/alpine-grafana
/ # ls /grafana/
LICENSE.md  NOTICE.md   README.md   VERSION     bin         conf        dashboards  data        logs        plugins     public      scripts     tools
/ #
```
alpine use ash shell

can not mkdir multi directory wiht `{}`

**Comment by mis4s** [comment]
Now work perfect, thanks ;)
